default:
  solo_url_tensorflow: "http://ec2-52-15-118-97.us-east-2.compute.amazonaws.com/rsconnect/content/3/"
  solo_url_plumber:    "http://ec2-52-15-118-97.us-east-2.compute.amazonaws.com/rsconnect/content/4/"

colorado:
  solo_url_tensorflow: "https://colorado.rstudio.com/rsc/content/2328/"
  solo_url_plumber:    "https://colorado.rstudio.com/rsc/content/2337/"
