default:
  solo_url_tensorflow: "https://colorado.rstudio.com/rsc/content/2328/"
  solo_url_plumber:    "https://colorado.rstudio.com/rsc/content/2337/"

colorado:
  solo_url_tensorflow: "https://colorado.rstudio.com/rsc/content/2328/"
  solo_url_plumber:    "https://colorado.rstudio.com/rsc/content/2337/"
